name: Deploy Astro site to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
  steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    
    - name: Build CV (LaTeX)
      uses: xu-cheng/latex-action@v3
      with:
        root_file: main.tex
        working_directory: cv

    - name: Move CV to public
      run: |
        mkdir -p public
        mv cv/main.pdf public/cv.pdf

    
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
